
export const DOCTOR = {
    id: 'doc_001',
    name: 'Dr. Ananya Krishnan',
    nameTa: 'டாக்டர் அனன்யா கிருஷ்ணன்',
    specialty: 'Cardiology & Diabetes',
    specialtyTa: 'இதயவியல் மற்றும் நீரிழிவு',
    hospital: 'Apollo Specialty Hospital',
    hospitalTa: 'அப்பல்லோ சிறப்பு மருத்துவமனை',
    patients: 128,
    avatar: null,
};


export let PATIENT_USER = {
    id: 'pat_001',
    name: 'Ravi Kumar',
    nameTa: 'ரவி குமார்',

    age: 58,
    gender: 'Male',
    genderTa: 'ஆண்',
    conditions: ['Diabetes T2', 'Hypertension'],
    conditionsTa: ['நீரிழிவு வகை 2', 'உயர் இரத்த அழுத்தம்'],
    riskScore: 72,
    riskLevel: 'high',
    trend: 'worsening',
    adherence: 68,
    emr: {
        diagnosisHistory: [
            { date: '2022-03-10', diagnosis: 'Type 2 Diabetes Mellitus' },
            { date: '2021-07-22', diagnosis: 'Essential Hypertension' },
        ],
        medications: [
            { name: 'Metformin 500mg', frequency: 'Twice daily' },
            { name: 'Amlodipine 5mg', frequency: 'Once daily' },
        ],
        comorbidities: ['Obesity BMI 28.4', 'Mild Dyslipidemia'],
    },
    labs: {
        hba1c: 8.2,
        cholesterol: 218,
        ecg: 'Sinus Tachycardia',
        creatinine: 1.1,
        date: '2026-02-20',
    },
    iotLive: {
        systolicBP: 148,
        diastolicBP: 94,
        bloodSugar: 210,
        heartRate: 92,
        lastSync: '2 min ago',
        abnormalCount: 3,
    },
    medications: ['Metformin 500mg', 'Amlodipine 5mg'],
    medicationsTa: ['மெட்ஃபோர்மின் 500 மி.கி', 'அம்லோடிபின் 5 மி.கி'],
    timeline: [
        {
            id: 't1',
            type: 'iot_alert',
            source: 'IoT',
            timestamp: '2026-02-27T06:30:00',
            title: 'Abnormal IoT Reading',
            titleTa: 'அசாதாரண IoT வாசிப்பு',
            detail: 'Systolic BP: 152 mmHg – above threshold',
            detailTa: 'சிஸ்டோலிக் BP: 152 mmHg – வரம்பை மீறியது',
            riskImpact: '+4',
        },
        {
            id: 't2',
            type: 'missed_med',
            source: 'Manual',
            timestamp: '2026-02-26T08:00:00',
            title: 'Missed Medication',
            titleTa: 'தவறிய மருந்து',
            detail: 'Metformin 500mg – Morning dose missed',
            detailTa: 'மெட்ஃபோர்மின் 500 மி.கி – காலை மருந்து தவறியது',
            riskImpact: '+3',
        },
        {
            id: 't3',
            type: 'risk_change',
            source: 'EMR',
            timestamp: '2026-02-25T14:00:00',
            title: 'Risk Score Change',
            titleTa: 'ஆபத்து மதிப்பெண் மாற்றம்',
            detail: 'Score increased from 68 to 72',
            detailTa: 'மதிப்பெண் 68 இலிருந்து 72 ஆக உயர்ந்தது',
            riskImpact: '+4',
            snapshot: {
                previousScore: 68,
                newScore: 72,
                delta: 4,
                vitalsAtTime: { bp: '148/94', sugar: 205, hr: 89 },
            },
        },
        {
            id: 't4',
            type: 'lab_entry',
            source: 'Lab',
            timestamp: '2026-02-20T10:00:00',
            title: 'Lab Report Added',
            titleTa: 'ஆய்வக அறிக்கை சேர்க்கப்பட்டது',
            detail: 'HbA1c: 8.2% (elevated), Cholesterol: 218 mg/dL',
            detailTa: 'HbA1c: 8.2% (உயர்ந்தது), கொழுப்பு: 218 மி.கி/டி.எல்.',
            riskImpact: '+5',
        },
        {
            id: 't5',
            type: 'alert_triggered',
            source: 'IoT',
            timestamp: '2026-02-19T22:10:00',
            title: 'Alert Triggered',
            titleTa: 'எச்சரிக்கை தூண்டப்பட்டது',
            detail: '3 consecutive abnormal BP readings detected',
            detailTa: '3 தொடர்ச்சியான அசாதாரண BP வாசிப்புகள் கண்டறியப்பட்டன',
            riskImpact: '+6',
        },
    ],
};

export const PATIENTS = [
    {
        id: 'p001',
        name: 'Ravi Kumar',
        nameTa: 'ரவி குமார்',
        age: 58,
        conditions: ['Diabetes', 'Hypertension'],
        conditionsTa: ['நீரிழிவு', 'உயர் இரத்த அழுத்தம்'],
        riskScore: 72,
        riskLevel: 'high',
        trend: 'worsening',
        adherence: 68,
        bp: '148/94',
        bloodSugar: 210,
        heartRate: 92,
        bmi: 28.4,
        emr: {
            diagnosisHistory: [
                { date: '2022-03-10', diagnosis: 'Type 2 Diabetes Mellitus' },
                { date: '2021-07-22', diagnosis: 'Essential Hypertension' },
            ],
            medications: [
                { name: 'Metformin 500mg', frequency: 'Twice daily' },
                { name: 'Amlodipine 5mg', frequency: 'Once daily' },
            ],
            comorbidities: ['Obesity BMI 28.4', 'Mild Dyslipidemia'],
        },
        labs: { hba1c: 8.2, cholesterol: 218, ecg: 'Sinus Tachycardia', creatinine: 1.1, date: '2026-02-20' },
        iotLive: { systolicBP: 148, diastolicBP: 94, bloodSugar: 210, heartRate: 92, lastSync: '2 min ago', abnormalCount: 3 },
        timeline: [
            { id: 't1', type: 'iot_alert', source: 'IoT', timestamp: '2026-02-27T06:30:00', title: 'Abnormal IoT Reading', titleTa: 'அசாதாரண IoT வாசிப்பு', detail: 'Systolic BP: 152 mmHg – above threshold', detailTa: 'சிஸ்டோலிக் BP: 152 mmHg – வரம்பை மீறியது', riskImpact: '+4' },
            { id: 't2', type: 'missed_med', source: 'Manual', timestamp: '2026-02-26T08:00:00', title: 'Missed Medication', titleTa: 'தவறிய மருந்து', detail: 'Metformin 500mg – Morning dose missed', detailTa: 'மெட்ஃபோர்மின் 500 மி.கி – காலை மருந்து தவறியது', riskImpact: '+3' },
            { id: 't3', type: 'risk_change', source: 'EMR', timestamp: '2026-02-25T14:00:00', title: 'Risk Score Change', titleTa: 'ஆபத்து மதிப்பெண் மாற்றம்', detail: 'Score increased from 68 to 72', detailTa: 'மதிப்பெண் 68 இலிருந்து 72 ஆக உயர்ந்தது', riskImpact: '+4' },
            { id: 't4', type: 'lab_entry', source: 'Lab', timestamp: '2026-02-20T10:00:00', title: 'Lab Report Added', titleTa: 'ஆய்வக அறிக்கை சேர்க்கப்பட்டது', detail: 'HbA1c: 8.2%, Cholesterol: 218', detailTa: 'HbA1c: 8.2%, கொழுப்பு: 218', riskImpact: '+5' },
        ],
    },

    {
        id: 'p002',
        name: 'Meena Sundaram',
        nameTa: 'மீனா சுந்தரம்',
        age: 45,
        conditions: ['Hypertension'],
        conditionsTa: ['உயர் இரத்த அழுத்தம்'],
        riskScore: 88,
        riskLevel: 'critical',
        trend: 'worsening',
        adherence: 42,
        bp: '165/102',
        bloodSugar: 140,
        heartRate: 98,
        bmi: 31.2,
        emr: {
            diagnosisHistory: [{ date: '2020-11-05', diagnosis: 'Stage 2 Hypertension' }],
            medications: [{ name: 'Losartan 50mg', frequency: 'Once daily' }],
            comorbidities: ['Obesity', 'Anxiety Disorder'],
        },
        labs: { hba1c: 6.1, cholesterol: 242, ecg: 'Left Ventricular Hypertrophy', creatinine: 1.3, date: '2026-02-18' },
        iotLive: { systolicBP: 165, diastolicBP: 102, bloodSugar: 140, heartRate: 98, lastSync: '5 min ago', abnormalCount: 5 },
        timeline: [
            { id: 't1', type: 'iot_alert', source: 'IoT', timestamp: '2026-02-27T07:10:00', title: 'Abnormal IoT Reading', titleTa: 'அசாதாரண IoT வாசிப்பு', detail: 'BP 168/104 – critically elevated', detailTa: 'BP 168/104 – ஆபத்தான அளவில் உயர்ந்தது', riskImpact: '+7' },
            { id: 't2', type: 'risk_change', source: 'EMR', timestamp: '2026-02-24T09:00:00', title: 'Risk Score Change', titleTa: 'ஆபத்து மதிப்பெண் மாற்றம்', detail: 'Score increased from 74 to 88', detailTa: 'மதிப்பெண் 74 இலிருந்து 88 ஆக உயர்ந்தது', riskImpact: '+14', snapshot: { previousScore: 74, newScore: 88, delta: 14, vitalsAtTime: { bp: '162/100', sugar: 138, hr: 95 } } },
        ],
    },
    {
        id: 'p003',
        name: 'Suresh Balamurugan',
        nameTa: 'சுரேஷ் பாலமுருகன்',
        age: 62,
        conditions: ['Cardiac Risk', 'Diabetes'],
        conditionsTa: ['இதய ஆபத்து', 'நீரிழிவு'],
        riskScore: 91,
        riskLevel: 'critical',
        trend: 'worsening',
        adherence: 35,
        bp: '170/108',
        bloodSugar: 248,
        heartRate: 104,
        bmi: 33.1,
        emr: {
            diagnosisHistory: [
                { date: '2019-06-14', diagnosis: 'Type 2 Diabetes Mellitus' },
                { date: '2018-02-28', diagnosis: 'Ischemic Heart Disease' },
            ],
            medications: [
                { name: 'Atorvastatin 40mg', frequency: 'Once daily' },
                { name: 'Metformin 1000mg', frequency: 'Twice daily' },
                { name: 'Aspirin 75mg', frequency: 'Once daily' },
            ],
            comorbidities: ['Ischemic Heart Disease', 'Chronic Kidney Disease Stage 2'],
        },
        labs: { hba1c: 9.8, cholesterol: 268, ecg: 'ST Depression', creatinine: 1.7, date: '2026-02-15' },
        iotLive: { systolicBP: 170, diastolicBP: 108, bloodSugar: 248, heartRate: 104, lastSync: '1 min ago', abnormalCount: 6 },
        timeline: [
            { id: 't1', type: 'alert_triggered', source: 'IoT', timestamp: '2026-02-27T05:45:00', title: 'Alert Triggered', titleTa: 'எச்சரிக்கை தூண்டப்பட்டது', detail: '3 consecutive abnormal readings – critical threshold', detailTa: '3 தொடர்ச்சியான அசாதாரண வாசிப்புகள் – ஆபத்தான வரம்பு', riskImpact: '+8' },
            { id: 't2', type: 'missed_med', source: 'Manual', timestamp: '2026-02-26T08:00:00', title: 'Missed Medication', titleTa: 'தவறிய மருந்து', detail: 'Missed 3 of last 5 doses', detailTa: 'கடந்த 5 மருந்துகளில் 3 தவறியது', riskImpact: '+5' },
        ],
    },
    {
        id: 'p004',
        name: 'Priya Lakshman',
        nameTa: 'பிரியா லட்சுமன்',
        age: 52,
        conditions: ['Diabetes T2'],
        conditionsTa: ['நீரிழிவு வகை 2'],
        riskScore: 54,
        riskLevel: 'medium',
        trend: 'stable',
        adherence: 82,
        bp: '130/84',
        bloodSugar: 168,
        heartRate: 78,
        bmi: 26.7,
        emr: {
            diagnosisHistory: [{ date: '2023-01-18', diagnosis: 'Type 2 Diabetes Mellitus' }],
            medications: [{ name: 'Glipizide 5mg', frequency: 'Once daily' }],
            comorbidities: ['Overweight'],
        },
        labs: { hba1c: 7.1, cholesterol: 195, ecg: 'Normal Sinus Rhythm', creatinine: 0.9, date: '2026-02-22' },
        iotLive: { systolicBP: 130, diastolicBP: 84, bloodSugar: 168, heartRate: 78, lastSync: '8 min ago', abnormalCount: 1 },
        timeline: [
            { id: 't1', type: 'lab_entry', source: 'Lab', timestamp: '2026-02-22T11:00:00', title: 'Lab Report Added', titleTa: 'ஆய்வக அறிக்கை சேர்க்கப்பட்டது', detail: 'HbA1c: 7.1% (borderline)', detailTa: 'HbA1c: 7.1% (எல்லை)', riskImpact: '+2' },
        ],
    },
    {
        id: 'p005',
        name: 'Anbu Selvan',
        nameTa: 'அன்பு செல்வன்',
        age: 39,
        conditions: ['Hypertension', 'Cardiac Risk'],
        conditionsTa: ['உயர் இரத்த அழுத்தம்', 'இதய ஆபத்து'],
        riskScore: 65,
        riskLevel: 'high',
        trend: 'improving',
        adherence: 74,
        bp: '142/90',
        bloodSugar: 130,
        heartRate: 86,
        bmi: 27.9,
        emr: {
            diagnosisHistory: [{ date: '2021-09-02', diagnosis: 'Essential Hypertension' }],
            medications: [{ name: 'Telmisartan 40mg', frequency: 'Once daily' }],
            comorbidities: ['Smoking History', 'Family History of CAD'],
        },
        labs: { hba1c: 5.8, cholesterol: 228, ecg: 'Normal Sinus Rhythm', creatinine: 1.0, date: '2026-02-19' },
        iotLive: { systolicBP: 142, diastolicBP: 90, bloodSugar: 130, heartRate: 86, lastSync: '3 min ago', abnormalCount: 2 },
        timeline: [
            { id: 't1', type: 'risk_change', source: 'EMR', timestamp: '2026-02-23T10:00:00', title: 'Risk Score Change', titleTa: 'ஆபத்து மதிப்பெண் மாற்றம்', detail: 'Score improved from 71 to 65', detailTa: 'மதிப்பெண் 71 இலிருந்து 65 ஆக மேம்பட்டது', riskImpact: '-6', snapshot: { previousScore: 71, newScore: 65, delta: -6, vitalsAtTime: { bp: '140/88', sugar: 128, hr: 84 } } },
        ],
    },
    {
        id: 'p006',
        name: 'Kavitha Raj',
        nameTa: 'கவிதா ராஜ்',
        age: 48,
        conditions: ['Diabetes'],
        conditionsTa: ['நீரிழிவு'],
        riskScore: 38,
        riskLevel: 'low',
        trend: 'improving',
        adherence: 93,
        bp: '122/78',
        bloodSugar: 118,
        heartRate: 72,
        bmi: 24.1,
        emr: {
            diagnosisHistory: [{ date: '2020-04-14', diagnosis: 'Type 2 Diabetes Mellitus' }],
            medications: [{ name: 'Metformin 500mg', frequency: 'Once daily' }],
            comorbidities: [],
        },
        labs: { hba1c: 6.4, cholesterol: 172, ecg: 'Normal Sinus Rhythm', creatinine: 0.8, date: '2026-02-21' },
        iotLive: { systolicBP: 122, diastolicBP: 78, bloodSugar: 118, heartRate: 72, lastSync: '4 min ago', abnormalCount: 0 },
        timeline: [],
    },
    {
        id: 'p007',
        name: 'Murugan Durai',
        nameTa: 'முருகன் துரை',
        age: 71,
        conditions: ['Cardiac Risk', 'Hypertension', 'Diabetes'],
        conditionsTa: ['இதய ஆபத்து', 'உயர் இரத்த அழுத்தம்', 'நீரிழிவு'],
        riskScore: 95,
        riskLevel: 'critical',
        trend: 'worsening',
        adherence: 28,
        bp: '182/115',
        bloodSugar: 290,
        heartRate: 112,
        bmi: 35.6,
        emr: {
            diagnosisHistory: [
                { date: '2016-08-10', diagnosis: 'Type 2 Diabetes Mellitus' },
                { date: '2015-03-22', diagnosis: 'Congestive Heart Failure' },
                { date: '2018-01-05', diagnosis: 'Stage 3 Hypertension' },
            ],
            medications: [
                { name: 'Furosemide 40mg', frequency: 'Once daily' },
                { name: 'Carvedilol 6.25mg', frequency: 'Twice daily' },
                { name: 'Insulin Glargine 20U', frequency: 'Once daily at night' },
            ],
            comorbidities: ['Congestive Heart Failure', 'Chronic Kidney Disease Stage 3', 'Morbid Obesity'],
        },
        labs: { hba1c: 11.2, cholesterol: 296, ecg: 'Atrial Fibrillation', creatinine: 2.1, date: '2026-02-10' },
        iotLive: { systolicBP: 182, diastolicBP: 115, bloodSugar: 290, heartRate: 112, lastSync: '1 min ago', abnormalCount: 7 },
        timeline: [
            { id: 't1', type: 'alert_triggered', source: 'IoT', timestamp: '2026-02-27T04:20:00', title: 'Alert Triggered', titleTa: 'எச்சரிக்கை தூண்டப்பட்டது', detail: 'BS 295 mg/dL – hyperglycemic crisis risk', detailTa: 'BS 295 மி.கி/டி.எல் – உயர் இரத்த சர்க்கரை நெருக்கடி ஆபத்து', riskImpact: '+9' },
            { id: 't2', type: 'missed_med', source: 'Manual', timestamp: '2026-02-26T07:00:00', title: 'Missed Medication', titleTa: 'தவறிய மருந்து', detail: '4 consecutive days insulin missed', detailTa: '4 தொடர்ச்சியான நாட்கள் இன்சுலின் தவறியது', riskImpact: '+8' },
        ],
    },
    {
        id: 'p008',
        name: 'Deepa Nathan',
        nameTa: 'தீபா நாதன்',
        age: 55,
        conditions: ['Hypertension'],
        conditionsTa: ['உயர் இரத்த அழுத்தம்'],
        riskScore: 42,
        riskLevel: 'medium',
        trend: 'stable',
        adherence: 88,
        bp: '136/86',
        bloodSugar: 108,
        heartRate: 74,
        bmi: 25.8,
        emr: {
            diagnosisHistory: [{ date: '2022-06-20', diagnosis: 'Essential Hypertension' }],
            medications: [{ name: 'Amlodipine 5mg', frequency: 'Once daily' }],
            comorbidities: [],
        },
        labs: { hba1c: 5.6, cholesterol: 188, ecg: 'Normal Sinus Rhythm', creatinine: 0.9, date: '2026-02-23' },
        iotLive: { systolicBP: 136, diastolicBP: 86, bloodSugar: 108, heartRate: 74, lastSync: '6 min ago', abnormalCount: 1 },
        timeline: [],
    },
    {
        id: 'p009',
        name: 'Selvi Pandian',
        nameTa: 'செல்வி பாண்டியன்',
        age: 33,
        conditions: ['Diabetes T2'],
        conditionsTa: ['நீரிழிவு வகை 2'],
        riskScore: 29,
        riskLevel: 'low',
        trend: 'improving',
        adherence: 96,
        bp: '118/76',
        bloodSugar: 102,
        heartRate: 68,
        bmi: 22.3,
        emr: {
            diagnosisHistory: [{ date: '2024-02-10', diagnosis: 'Type 2 Diabetes Mellitus – Early Stage' }],
            medications: [{ name: 'Metformin 500mg', frequency: 'Once daily' }],
            comorbidities: [],
        },
        labs: { hba1c: 5.9, cholesterol: 158, ecg: 'Normal Sinus Rhythm', creatinine: 0.7, date: '2026-02-24' },
        iotLive: { systolicBP: 118, diastolicBP: 76, bloodSugar: 102, heartRate: 68, lastSync: '9 min ago', abnormalCount: 0 },
        timeline: [],
    },
    {
        id: 'p010',
        name: 'Karthi Velan',
        nameTa: 'கார்த்தி வேலன்',
        age: 66,
        conditions: ['Cardiac Risk', 'Diabetes'],
        conditionsTa: ['இதய ஆபத்து', 'நீரிழிவு'],
        riskScore: 78,
        riskLevel: 'high',
        trend: 'stable',
        adherence: 61,
        bp: '152/96',
        bloodSugar: 222,
        heartRate: 88,
        bmi: 29.5,
        emr: {
            diagnosisHistory: [
                { date: '2020-08-14', diagnosis: 'Type 2 Diabetes Mellitus' },
                { date: '2019-12-01', diagnosis: 'Peripheral Arterial Disease' },
            ],
            medications: [
                { name: 'Clopidogrel 75mg', frequency: 'Once daily' },
                { name: 'Metformin 500mg', frequency: 'Twice daily' },
            ],
            comorbidities: ['Peripheral Arterial Disease', 'Dyslipidemia'],
        },
        labs: { hba1c: 8.8, cholesterol: 252, ecg: 'Right Bundle Branch Block', creatinine: 1.4, date: '2026-02-17' },
        iotLive: { systolicBP: 152, diastolicBP: 96, bloodSugar: 222, heartRate: 88, lastSync: '7 min ago', abnormalCount: 3 },
        timeline: [
            { id: 't1', type: 'lab_entry', source: 'Lab', timestamp: '2026-02-17T09:30:00', title: 'Lab Report Added', titleTa: 'ஆய்வக அறிக்கை சேர்க்கப்பட்டது', detail: 'HbA1c: 8.8% – worsening glycemic control', detailTa: 'HbA1c: 8.8% – மோசமடையும் சர்க்கரை கட்டுப்பாடு', riskImpact: '+5' },
        ],
    },
];

export const ALERTS = [
    {
        id: 'a001',
        patientId: 'p003',
        patientName: 'Suresh Balamurugan',
        patientNameTa: 'சுரேஷ் பாலமுருகன்',
        type: 'critical',
        message: 'BP critically elevated: 170/108. Immediate review needed.',
        messageTa: 'இரத்த அழுத்தம் அபாயகரமாக உயர்ந்துள்ளது: 170/108. உடனடி மதிப்பீடு தேவை.',
        time: '10 min ago',
        timeTa: '10 நிமிடங்களுக்கு முன்',
    },
    {
        id: 'a002',
        patientId: 'p007',
        patientName: 'Murugan Durai',
        patientNameTa: 'முருகன் துரை',
        type: 'critical',
        message: 'Blood sugar 290 mg/dL. Risk of hyperglycemic crisis.',
        messageTa: 'இரத்த சர்க்கரை 290 மி.கி/டி.எல். உயர் இரத்த சர்க்கரை நெருக்கடி ஆபத்து.',
        time: '25 min ago',
        timeTa: '25 நிமிடங்களுக்கு முன்',
    },
    {
        id: 'a003',
        patientId: 'p002',
        patientName: 'Meena Sundaram',
        patientNameTa: 'மீனா சுந்தரம்',
        type: 'deteriorating',
        message: 'Risk score increased from 74 to 88 in 3 days.',
        messageTa: 'அபாய மதிப்பெண் 3 நாட்களில் 74 இலிருந்து 88 ஆக உயர்ந்துள்ளது.',
        time: '1 hr ago',
        timeTa: '1 மணி நேரத்திற்கு முன்',
    },
    {
        id: 'a004',
        patientId: 'p001',
        patientName: 'Ravi Kumar',
        patientNameTa: 'ரவி குமார்',
        type: 'deteriorating',
        message: 'Worsening trend. Medication adherence dropped to 68%.',
        messageTa: 'மோசமடைந்து வரும் போக்கு. மருந்து இணக்கம் 68% ஆக குறைந்துள்ளது.',
        time: '2 hrs ago',
        timeTa: '2 மணி நேரத்திற்கு முன்',
    },
    {
        id: 'a005',
        patientId: 'p007',
        patientName: 'Murugan Durai',
        patientNameTa: 'முருகன் துரை',
        type: 'non_adherent',
        message: 'Missed medication 4 days in a row. Adherence at 28%.',
        messageTa: 'தொடர்ந்து 4 நாட்கள் மருந்து தவறவிட்டார். இணக்கம் 28% மட்டுமே.',
        time: '3 hrs ago',
        timeTa: '3 மணி நேரத்திற்கு முன்',
    },
    {
        id: 'a006',
        patientId: 'p005',
        patientName: 'Anbu Selvan',
        patientNameTa: 'அன்பு செல்வன்',
        type: 'non_adherent',
        message: 'Missed 3 of last 5 scheduled medication doses.',
        messageTa: 'கடைசி 5 மருந்து அட்டவணையில் 3 தவறவிட்டார்.',
        time: '4 hrs ago',
        timeTa: '4 மணி நேரத்திற்கு முன்',
    },
    {
        id: 'a007',
        patientId: 'p003',
        patientName: 'Suresh Balamurugan',
        patientNameTa: 'சுரேஷ் பாலமுருகன்',
        type: 'iot_spike',
        message: 'IoT: Heart rate spike 118 bpm detected. Monitor closely.',
        messageTa: 'IoT: இதய துடிப்பு 118 bpm கண்டறியப்பட்டது. கவனமாக கண்காணிக்கவும்.',
        time: '8 min ago',
        timeTa: '8 நிமிடங்களுக்கு முன்',
    },
    {
        id: 'a008',
        patientId: 'p001',
        patientName: 'Ravi Kumar',
        patientNameTa: 'ரவி குமார்',
        type: 'iot_spike',
        message: 'IoT: Blood pressure 158/102 — above alert threshold.',
        messageTa: 'IoT: இரத்த அழுத்தம் 158/102 — எச்சரிக்கை வரம்பை மீறியது.',
        time: '15 min ago',
        timeTa: '15 நிமிடங்களுக்கு முன்',
    },
];


export const HEALTH_TRENDS = {
    bp: [
        { day: 'Mon', value: 138 },
        { day: 'Tue', value: 142 },
        { day: 'Wed', value: 148 },
        { day: 'Thu', value: 145 },
        { day: 'Fri', value: 150 },
        { day: 'Sat', value: 148 },
        { day: 'Sun', value: 152 },
    ],
    bloodSugar: [
        { day: 'Mon', value: 180 },
        { day: 'Tue', value: 195 },
        { day: 'Wed', value: 210 },
        { day: 'Thu', value: 200 },
        { day: 'Fri', value: 215 },
        { day: 'Sat', value: 208 },
        { day: 'Sun', value: 222 },
    ],
    heartRate: [
        { day: 'Mon', value: 78 },
        { day: 'Tue', value: 82 },
        { day: 'Wed', value: 88 },
        { day: 'Thu', value: 86 },
        { day: 'Fri', value: 90 },
        { day: 'Sat', value: 92 },
        { day: 'Sun', value: 88 },
    ],
    riskScore: [
        { day: 'Mon', value: 62 },
        { day: 'Tue', value: 65 },
        { day: 'Wed', value: 68 },
        { day: 'Thu', value: 67 },
        { day: 'Fri', value: 70 },
        { day: 'Sat', value: 72 },
        { day: 'Sun', value: 72 },
    ],
};

/**
 * Switch the active patient — mutates PATIENT_USER in-place so
 * all screens that imported it automatically pick up the new data.
 * Normalizes the incoming patient to fill any missing fields that
 * PatientDashboard and other screens depend on.
 */
export function setActivePatient(newPatient) {
    // Build a normalized patient merging incoming data with safe defaults
    const normalized = {
        id: newPatient.id || 'pat_unknown',
        name: newPatient.name || 'Unknown Patient',
        nameTa: newPatient.nameTa || newPatient.name || 'நோயாளி',
        age: newPatient.age || 0,
        gender: newPatient.gender || 'Male',
        genderTa: newPatient.genderTa || (newPatient.gender === 'Female' ? 'பெண்' : 'ஆண்'),
        conditions: newPatient.conditions || [],
        conditionsTa: newPatient.conditionsTa || newPatient.conditions || [],
        riskScore: newPatient.riskScore || newPatient.calculatedScore || 50,
        riskLevel: newPatient.riskLevel || newPatient.calculatedLevel || 'medium',
        trend: newPatient.trend || 'stable',
        adherence: newPatient.adherence || 70,
        // Medications — derive from emr if top-level list is missing
        medications: newPatient.medications || (newPatient.emr?.medications?.map(m => m.name) ?? []),
        medicationsTa: newPatient.medicationsTa || (newPatient.emr?.medications?.map(m => m.name) ?? []),
        emr: newPatient.emr || { diagnosisHistory: [], medications: [], comorbidities: [] },
        labs: newPatient.labs || { hba1c: 6.0, cholesterol: 180, ecg: 'Normal', creatinine: 1.0, date: '2026-01-01' },
        iotLive: newPatient.iotLive || {
            systolicBP: parseInt((newPatient.bp || '120/80').split('/')[0]) || 120,
            diastolicBP: parseInt((newPatient.bp || '120/80').split('/')[1]) || 80,
            bloodSugar: newPatient.bloodSugar || 110,
            heartRate: newPatient.heartRate || 72,
            lastSync: '1 min ago',
            abnormalCount: 0,
        },
        timeline: Array.isArray(newPatient.timeline) ? newPatient.timeline : [],
    };

    // Clear existing keys and assign normalized data
    Object.keys(PATIENT_USER).forEach(k => delete PATIENT_USER[k]);
    Object.assign(PATIENT_USER, normalized);
}


